[project]
name = "todo-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.4",
    "aiosqlite>=0.21.0",
    "alembic>=1.14.1",
    "fastapi[all]>=0.115.8",
    "redis>=5.2.1",
]
